### ISSUE TITLE
OneDrive GUI does not start.

### ISSUE THREAD

**Issue by Tealdris** [bpozdena/OneDriveGUI#110]
Hi. I have a problem with OneDrive GUI. OneDrive itself is working.
My specs:
Os - ubuntu 22.04
OneDrive ver 2.14.13
OneDriveGUI ver - OneDriveGUI-1.0.1-x86_64.AppImage and OneDriveGUI-1.0.2-x86_64.AppImage were tested

The problem appears in three cases.

1. If I start AppImage from GUI - a black rectangular appears for one second. After that, nothing happens.
2. If I start AppImage from the terminal - I get an error 

``Gtk-Message: 11:46:53.710: Failed to load module "canberra-gtk-module"``. 

Fix from link with installing "canberra-gtk-module", unfortunately, not working. 

(`` https://askubuntu.com/questions/208431/failed-to-load-module-canberra-gtk-module ``)

Text of an error.

```
tealdris@tufub:~/onedrive$ ./OneDriveGUI-1.0.1-x86_64.AppImage 
2023-06-05 11:46:53,168 [OneDriveGUI.py:2789][fn=get_installed_client_version][DEBUG] - [GUI] Installed client version is 2413
2023-06-05 11:46:53,170 [OneDriveGUI.py:2824][fn=create_global_config][DEBUG] - [GUI] - loading default config {'onedrive': {'sync_dir': '"~/OneDrive"', 'skip_file': '"~*|.~*|*.tmp"', 'monitor_interval': '"300"', 'skip_dir': '""', 'log_dir': '"/var/log/onedrive/"', 'drive_id': '""', 'upload_only': '"false"', 'check_nomount': '"false"', 'check_nosync': '"false"', 'download_only': '"false"', 'disable_notifications': '"false"', 'disable_upload_validation': '"false"', 'enable_logging': '"false"', 'force_http_11': '"false"', 'local_first': '"false"', 'no_remote_delete': '"false"', 'skip_symlinks': '"false"', 'debug_https': '"false"', 'skip_dotfiles': '"false"', 'dry_run': '"false"', 'min_notify_changes': '"5"', 'monitor_log_frequency': '"5"', 'monitor_fullscan_frequency': '"10"', 'sync_root_files': '"false"', 'classify_as_big_delete': '"1000"', 'user_agent': '""', 'remove_source_files': '"false"', 'skip_dir_strict_match': '"false"', 'application_id': '""', 'resync': '"false"', 'bypass_data_preservation': '"false"', 'azure_ad_endpoint': '""', 'azure_tenant_id': '"common"', 'sync_business_shared_folders': '"false"', 'sync_dir_permissions': '"700"', 'sync_file_permissions': '"600"', 'rate_limit': '"125000000"', 'operation_timeout': '"3600"', 'webhook_enabled': '"false"', 'webhook_public_url': '""', 'webhook_listening_host': '""', 'webhook_listening_port': '"8888"', 'webhook_expiration_interval': '"86400"', 'webhook_renewal_interval': '"43200"'}}
2023-06-05 11:46:53,170 [OneDriveGUI.py:2863][fn=create_global_config][DEBUG] - [GUI]{'ilyaradomskiy@mail.ru': {'config_file': '/home/tealdris/.config/onedrive/accounts/ilyaradomskiy@mail.ru/config', 'auto_sync': 'False', 'account_type': 'Personal', 'free_space': '4.9GiB', 'onedrive': {}}}
2023-06-05 11:46:53,170 [OneDriveGUI.py:2872][fn=save_global_config][DEBUG] - [save_global_config]:[1]{'ilyaradomskiy@mail.ru': {'config_file': '/home/tealdris/.config/onedrive/accounts/ilyaradomskiy@mail.ru/config', 'auto_sync': 'False', 'account_type': 'Personal', 'free_space': '4.9GiB', 'onedrive': {}}}
2023-06-05 11:46:53,568 [OneDriveGUI.py:2929][fn=save_global_config][INFO] - ilyaradomskiy@mail.ru config saved
2023-06-05 11:46:53,568 [OneDriveGUI.py:2931][fn=save_global_config][INFO] - All configs saved
2023-06-05 11:46:53,569 [OneDriveGUI.py:2932][fn=save_global_config][DEBUG] - {'ilyaradomskiy@mail.ru': {'config_file': '/home/tealdris/.config/onedrive/accounts/ilyaradomskiy@mail.ru/config', 'auto_sync': 'False', 'account_type': 'Personal', 'free_space': '4.9GiB', 'onedrive': {}}}
Gtk-Message: 11:46:53.710: Failed to load module "canberra-gtk-module"
Gtk-Message: 11:46:53.710: Failed to load module "canberra-gtk-module"
2023-06-05 11:46:53,924 [OneDriveGUI.py:2950][fn=main_window_start_state][INFO] - [GUI] Starting OneDriveGUI maximized
2023-06-05 11:46:53,925 [OneDriveGUI.py:1075][fn=__init__][INFO] - ilyaradomskiy@mail.ru
Traceback (most recent call last):
  File "/tmp/.mount_OneDritwuYdH//usr/src/OneDriveGUI.py", line 3044, in <module>
    profile_settings_window = ProfileSettingsWindow()
  File "/tmp/.mount_OneDritwuYdH//usr/src/OneDriveGUI.py", line 1077, in __init__
    self.page = ProfileSettingsPage(profile)
  File "/tmp/.mount_OneDritwuYdH//usr/src/OneDriveGUI.py", line 1200, in __init__
    self.configure_profile_settings_page()
  File "/tmp/.mount_OneDritwuYdH//usr/src/OneDriveGUI.py", line 1440, in configure_profile_settings_page
    self.lineEdit_sync_dir.setText(self.temp_profile_config["onedrive"]["sync_dir"].strip('"'))
KeyError: 'sync_dir'

```

3. If I add `sudo` and start AppImage from the terminal - I get a `welcome` window like Onedrive was not configured before. But if I try to login into my account also get an error

```
2023-06-05 12:49:53,006 [OneDriveGUI.py:265][fn=isComplete][INFO] - Wizard page is complete.

(python3:55205): Gtk-WARNING **: 12:49:56.379: Could not find the icon 'user-home-symbolic-ltr'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
	http://icon-theme.freedesktop.org/releases

(python3:55205): Gtk-WARNING **: 12:49:56.380: Could not load a pixbuf from /org/gtk/libgtk/icons/16x16/status/image-missing.png.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Aborted
```

I was trying to reinstall Onedrive, but it resulted in the errors above.
Thank you for your help in advance.

**Comment by Tealdris** [comment]
There was problem with my system, clean ubuntu solve problem
