### ISSUE TITLE
Error when importing profile

### ISSUE THREAD

**Issue by GalaxyCurse** [bpozdena/OneDriveGUI#17]
`  File "/home/curse/Devel/OneDriveGUI-main/src/OneDriveGUI.py", line 1333, in <lambda>
    self.refresh_process_status.timeout.connect(lambda: self.onedrive_process_status())
  File "/home/curse/Devel/OneDriveGUI-main/src/OneDriveGUI.py", line 1360, in onedrive_process_status
    self.profile_status_pages[profile_name].label_status.setText("stopped")
KeyError: `'my@email.address'`
`

I've tried both with and without my email address in the "Profile Name" field, but same result.
It does write a config though, but the "next" button is unavailable. Only "back" and "cancel".

`[my@email.address]
config_file = /home/curse/.config/onedrive/config
enable_debug = False
mode = monitor
`

So I close down the gui and try again this error comes up.

`$ python OneDriveGUI.py 
Traceback (most recent call last):
  File "/home/curse/Devel/OneDriveGUI-main/src/OneDriveGUI.py", line 1615, in <module>
    settings_window = SettingsWindow()
  File "/home/curse/Devel/OneDriveGUI-main/src/OneDriveGUI.py", line 476, in __init__
    self.page = ProfileSettingsPage(profile)
  File "/home/curse/Devel/OneDriveGUI-main/src/OneDriveGUI.py", line 725, in __init__
    self.checkBox_sync_root_files.setChecked(self.get_check_box_state("sync_root_files"))
  File "/home/curse/Devel/OneDriveGUI-main/src/OneDriveGUI.py", line 972, in get_check_box_state
    return self.temp_profile_config[f"{property}"].strip('"') in "true"
KeyError: 'sync_root_files'
`

I'm not sure if the error is at my end or...

**Comment by GalaxyCurse** [comment]
I can confirm that it's fixed.
