### ISSUE TITLE
Application does not start throwing "Unable to get dbus proxy"

### ISSUE THREAD

**Issue by progaddicted** [bpozdena/OneDriveGUI#25]
Installed on Fedora 34 [5.16.9-100.fc34.x86_64 x86_64]

### Here is what happens when trying to launch the application
[marco@asus-tovis src]$>python OneDriveGUI.py 
2022-02-19 22:09:36,501 - INFO - mspina@tovisconsulenze.onmicrosoft.com
2022-02-19 22:10:01,589 - DEBUG - Unable to get dbus proxy: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
2022-02-19 22:10:26,615 - DEBUG - Unable to get dbus proxy: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Traceback (most recent call last):
  File "/home/marco/OneDriveGUI/src/OneDriveGUI.py", line 1690, in <module>
    settings_window = SettingsWindow()
  File "/home/marco/OneDriveGUI/src/OneDriveGUI.py", line 507, in __init__
    self.page = ProfileSettingsPage(profile)
  File "/home/marco/OneDriveGUI/src/OneDriveGUI.py", line 753, in __init__
    self.lineEdit_sync_dir.setText(self.temp_profile_config["sync_dir"].strip('"'))
KeyError: 'sync_dir'
### Configuration and log files
(.txt extensions added since files with no extension are not accepted)
[onedrivegui.log](https://github.com/bpozdena/OneDriveGUI/files/8103034/onedrivegui.log)
[profiles.txt](https://github.com/bpozdena/OneDriveGUI/files/8103038/profiles.txt)
[config.txt](https://github.com/bpozdena/OneDriveGUI/files/8103040/config.txt)
[sync_list.txt](https://github.com/bpozdena/OneDriveGUI/files/8103045/sync_list.txt)
Please note that the directory /var/log/onedrive/ is empty

**Comment by bpozdena** [comment]
Thanks for the detailed issue description.

By the looks of it it seems to me as if the config file was not imported correctly via the GUI wizard. Not sure why, but I can think of to potential improvements to mitigate this. I will try to provide fix for both soon. 

A theoretical temporary fix for you should be simply importing the config file again:
1)Delete ```~/.config/onedrive-gui/profiles```
2)Open the GUI, and import the config again. Ensure path to the config file in the wizard is complete ```/home/marco/.config/onedrive/config```.

**Comment by progaddicted** [comment]
Hello, re-installing from scratch solved the issue, but not definitely.
After the setup the GUI starts, but the version check fails, saying the OneDrive latest version is 2.4.15, which is actually not true for Fedora34 (see the pictures)

![OneDriveGUI_version check](https://user-images.githubusercontent.com/54311010/155206167-ba7e3096-6d33-4025-892d-7a533f13ddef.png)

![OneDrive releases](https://user-images.githubusercontent.com/54311010/155206189-f705cfba-50d2-4126-ab56-ba0bd6bbcdc4.png)

Moreover, in the GUI imported config file all the entries got uncommented, so that the OneDrive CLI fails throwing "Unknown key in config file: ......." where keys are: "operation_timeout", and the "webhook_..." ones.

After commenting the "unknown keys" in the config file the CLI works fine, but the GUI throws again "Unable to get dbus..."; looks like that altering in any way the config file causes the crash.

[config.txt](https://github.com/bpozdena/OneDriveGUI/files/8119750/config.txt)

**Comment by bpozdena** [comment]
All this is expected behavior. You're using an unsupported version of the OneDrive client. Install the latest version from source or ask the package maintainer to update it.
