### ISSUE TITLE
OneDriveGUI-1.0.2-x86_64 fails to start.

### ISSUE THREAD

**Issue by Tokn59** [bpozdena/OneDriveGUI#98]
Hi, I have a Linux Mint installation (Vera Release) with onedrive v2.4.23-19-g5945edc running. Authorisation has been done succesfully.

However when I try to start the OneDriveGUI-1.0.2-x86_64 nothing seems to happen. (Permission set ok) he log shows 

tmp-.mount _OneDriIXbatu.mount: Deactivaed Successfully.

On a similar machine with the exact same versions of OS, onedrive and the gui it does work perfect. Any clue as what is wrong ?

thanks for your help !!!

![image](https://user-images.githubusercontent.com/9215231/230604991-58b1499f-45d9-4f5f-8169-cabec063f427.png)

**Comment by bpozdena** [comment]
@Tokn59 , please run the AppImage from terminal and share the output.

**Comment by Tokn59** [comment]
tony@tony-Latitude-E5550:~/Apps$ ./OneDriveGUI-1.0.2-x86_64.AppImage
2023-04-07 14:19:53,026 [OneDriveGUI.py:3082][fn=config_client_bin_path][INFO] - Onedrive client location: 'onedrive'
2023-04-07 14:19:53,038 [OneDriveGUI.py:2847][fn=get_installed_client_version][DEBUG] - [GUI] Installed client version is 2423
2023-04-07 14:19:53,039 [OneDriveGUI.py:2882][fn=create_global_config][DEBUG] - [GUI] - loading default config {'onedrive': {'sync_dir': '"~/OneDrive"', 'monitor_interval': '"300"', 'log_dir': '"/var/log/onedrive/"', 'drive_id': '""', 'upload_only': '"false"', 'check_nomount': '"false"', 'check_nosync': '"false"', 'download_only': '"false"', 'disable_notifications': '"false"', 'disable_upload_validation': '"false"', 'enable_logging': '"false"', 'force_http_11': '"false"', 'local_first': '"false"', 'no_remote_delete': '"false"', 'skip_symlinks': '"false"', 'debug_https': '"false"', 'skip_dotfiles': '"false"', 'dry_run': '"false"', 'min_notify_changes': '"5"', 'monitor_log_frequency': '"5"', 'monitor_fullscan_frequency': '"10"', 'sync_root_files': '"false"', 'classify_as_big_delete': '"1000"', 'user_agent': '""', 'remove_source_files': '"false"', 'skip_dir_strict_match': '"false"', 'application_id': '""', 'resync': '"false"', 'bypass_data_preservation': '"false"', 'azure_ad_endpoint': '""', 'azure_tenant_id': '"common"', 'sync_business_shared_folders': '"false"', 'sync_dir_permissions': '"700"', 'sync_file_permissions': '"600"', 'rate_limit': '"125000000"', 'operation_timeout': '"3600"', 'webhook_enabled': '"false"', 'webhook_public_url': '""', 'webhook_listening_host': '""', 'webhook_listening_port': '"8888"', 'webhook_expiration_interval': '"86400"', 'webhook_renewal_interval': '"43200"', 'skip_file': '"~*|.~*|*.tmp"', 'skip_dir': '""'}}
Traceback (most recent call last):
  File "/tmp/.mount_OneDriQ8WS0h//usr/src/OneDriveGUI.py", line 3101, in <module>
    global_config = create_global_config()
  File "/tmp/.mount_OneDriQ8WS0h//usr/src/OneDriveGUI.py", line 2891, in create_global_config
    _od_config = read_config(profile_config_file)
  File "/tmp/.mount_OneDriQ8WS0h//usr/src/OneDriveGUI.py", line 2803, in read_config
    with open(config_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/doc/onedrive/config'

**Comment by Tokn59** [comment]
When I run onedrive --synchronize from a terminal that does work ...

**Comment by bpozdena** [comment]
It looks like you are trying to load onedrive config
'/usr/share/doc/onedrive/config' which does not exists.
You can adjust your path to valid config file in the GUI profile config
~/.config/onedrive-gui/. Or delete this directory completely, start the Gui
and follow the setup wizard.

**Comment by Tokn59** [comment]
Deleting the file ~/.config/onedrive-gui/profiles did the job ! Now I can create a new profile !

THANK YOU SO MUCH !!!!!

**Comment by bpozdena** [comment]
No problem. I will keep this issue open and will try to handle this in a nicer way in the future.
